#SELINUX
        - name: Desabilitando o SeLinux
          selinux: policy=targeted state=disabled
#FIREWALLD
        - name: Desabilitando o firewalld
          systemd: name=firewalld state=stopped enabled=no
#TIMEZONE
        - name: Ajustando o timezone do sistema
          timezone: name=America/Sao_Paulo
#IDIOMA
        - name: Alterando o idioma do sistema
          command: /bin/localectl set-locale LANG=pt_BR.utf8
#TECLADO
        - name: Alterando o teclado do sistema
          command: /bin/localectl set-keymap br-abnt2

        - name: Instalando couchbase
          yum:
            name:  https://packages.couchbase.com/releases/5.0.1/couchbase-server-community-5.0.1-centos7.x86_64.rpm
            state: installed
#NTP
        - name: Instalando o NTP/ntpdate
          yum: pkg={{ item }} state=installed
          with_items:
          - ntp

        - name: Instalando o etcd
          yum: pkg={{ item }} state=installed
          with_items:
          - etcd

        - name: start couchbase-server
          command: systemctl start couchbase-server

        - name: wait couchbase
          command: sleep 30

        - name: pegando chave etcd
          shell: etcdctl --endpoints="http://10.172.60.163:2379,http://10.172.60.187:2379,http://10.172.60.188:2379" ls /couchbase 2> /dev/null | head -1 | xargs etcdctl --endpoints="http://10.172.60.163:2379,http://10.172.60.187:2379,http://10.172.60.188:2379" get
          register: output
          ignore_errors: yes


        - name: add nó etcd
          shell: etcdctl --endpoints="http://10.172.60.163:2379,http://10.172.60.187:2379,http://10.172.60.188:2379" mkdir /couchbase && etcdctl --endpoints="http://10.172.60.163:2379,http://10.172.60.187:2379,http://10.172.60.188:2379" set /couchbase/{{ ansible_enp0s3.ipv4.address }} {{ ansible_enp0s3.ipv4.address }}
          when: output is failed

        - name: init cluster
          shell: /opt/couchbase/bin/couchbase-cli cluster-init -c {{ ansible_enp0s3.ipv4.address }}:8091 --cluster-username Administrator  --cluster-password password --services data,index,query,fts  --cluster-ramsize 256 --cluster-index-ramsize 500
          when: output is failed

        - name: create database app-db
          shell: /opt/couchbase/bin/couchbase-cli bucket-create -c {{ ansible_enp0s3.ipv4.address }}:8091 --username Administrator  --password password --bucket app-db --bucket-type couchbase  --bucket-ramsize 200
          when: output is failed

        - name: get master-node
          shell:  etcdctl --endpoints="http://10.172.60.163:2379,http://10.172.60.187:2379,http://10.172.60.188:2379" ls couchbase | head -1 | awk -F'/' '{ print $3}'
          register: output2

        - name: create join cluster
          shell: /opt/couchbase/bin/couchbase-cli server-add --cluster={{ output2.stdout }}:8091  --user Administrator --password password   --server-add={{ ansible_enp0s3.ipv4.address }}:8091  --server-add-username=Administrator --server-add-password=password
          when: output is succeeded
